env:
    CIRRUS_SHELL: bash

task:
  name: "ld"
  timeout_in: 180m
  container:
      image: Ubuntu:latest
      cpu: 8
      memory: 20G

  test:
    - wget https://github.com/coder/code-server/releases/download/v4.4.0/code-server-4.4.0-linux-amd64.tar.gz
    - tar xvzf code-server-4.4.0-linux-amd64.tar.gz
    - cd code-server-4.4.0-linux-amd64/bin
    - ./code-server --auth none
