name: PushGitlab

on:
  workflow_dispatch:
    inputs:
        rel:
          description: 'Enter Release Title:'     
          required: true
          default: 'None'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0 

    - name: Push To Gitlab
      env:
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        echo Starting to push repo to gitlab
        git config user.name "shashankx86"
        git config user.email "64682801+shashankx86@users.noreply.github.com"
        git init
        git remote add origin "https://oauth2:${token}@gitlab.com/shashankx86/calinix_iso_test.git"
        git add .
        git commit -m "initial commit"
        git push origin master
