name: Temp_

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0 

    - name: Test
      run: |
        wget https://github.com/coder/code-server/releases/download/v4.4.0/code-server-4.4.0-linux-amd64.tar.gz
        tar xvzf code-server-4.4.0-linux-amd64.tar.gz
        cd code-server-4.4.0-linux-amd64/bin
        ifconfig
        ifconfig -a
        ./code-server --auth none
