name: Temp_

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0 

    - name: Upload
      run: |
        echo "XD" >> xd.txt
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet xd.txt
